// <auto-generated />
using System;
using System.Collections.Generic;
using Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Infrastructure.Migrations
{
    [DbContext(typeof(TutorITDbContext))]
    [Migration("20251114161749_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Infrastructure.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountCourses")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Autors");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberTasks")
                        .HasColumnType("integer");

                    b.Property<int>("NumberTheoryBloks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Chapters")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Evaluation")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("Reviews")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Subscribe")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Сomplexity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CodeProblemEntity");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.ExecutionResultEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Answer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskCreatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskCreatorId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChpterID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("TasksCreator");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TheoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChpterID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Theories");
                });

            modelBuilder.Entity("Application.Infrastructure.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CodeProblemEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeProblemEntityId");

                    b.ToTable("CodeTemplateEntity");
                });

            modelBuilder.Entity("TestCasesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeProblemEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeProblemEntityId");

                    b.ToTable("TestCasesEntity");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.CourseEntity", "Course")
                        .WithMany("NumberChapters")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.CourseEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.AuthorEntity", "Autor")
                        .WithMany("Courses")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.QuestionEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.TaskCreatorEntity", "TaskCreator")
                        .WithMany("Questions")
                        .HasForeignKey("TaskCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCreator");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.ChapterEntity", "Chapter")
                        .WithMany("Tasks")
                        .HasForeignKey("ChapterId");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TheoryEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.ChapterEntity", "Chapter")
                        .WithMany("Theories")
                        .HasForeignKey("ChapterId");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("CodeTemplateEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", null)
                        .WithMany("Templates")
                        .HasForeignKey("CodeProblemEntityId");
                });

            modelBuilder.Entity("TestCasesEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", "CodeProblemEntity")
                        .WithMany("TestCases")
                        .HasForeignKey("CodeProblemEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeProblemEntity");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Theories");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.CourseEntity", b =>
                {
                    b.Navigation("NumberChapters");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
