// <auto-generated />
using System;
using System.Collections.Generic;
using Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Infrastructure.Migrations
{
    [DbContext(typeof(TutorITDbContext))]
    partial class TutorITDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberTasks")
                        .HasColumnType("integer");

                    b.Property<int>("NumberTheoryBloks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Chapters")
                        .HasColumnType("integer");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Evaluation")
                        .HasColumnType("double precision");

                    b.Property<string>("Pl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Reviews")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Subscribe")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Answer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskCreatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskCreatorId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterID");

                    b.ToTable("TasksCreator");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TheoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChapterID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterID");

                    b.ToTable("Theories");
                });

            modelBuilder.Entity("Application.Infrastructure.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.CourseEntity", "Course")
                        .WithMany("NumberChapters")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.QuestionEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.TaskCreatorEntity", "TaskCreator")
                        .WithMany("Questions")
                        .HasForeignKey("TaskCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCreator");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.ChapterEntity", "Chapter")
                        .WithMany("Tasks")
                        .HasForeignKey("ChapterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TheoryEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.ChapterEntity", "Chapter")
                        .WithMany("Theories")
                        .HasForeignKey("ChapterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.ChapterEntity", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Theories");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.CourseEntity", b =>
                {
                    b.Navigation("NumberChapters");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.TaskCreatorEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
