// <auto-generated />
using System;
using Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Infrastructure.Migrations
{
    [DbContext(typeof(TutorITDbContext))]
    partial class TutorITDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CodeProblemEntity");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.ExecutionResultEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("CodeTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CodeProblemEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeProblemEntityId");

                    b.ToTable("CodeTemplateEntity");
                });

            modelBuilder.Entity("TestCasesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeProblemEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeProblemEntityId");

                    b.ToTable("TestCasesEntity");
                });

            modelBuilder.Entity("CodeTemplateEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", null)
                        .WithMany("Templates")
                        .HasForeignKey("CodeProblemEntityId");
                });

            modelBuilder.Entity("TestCasesEntity", b =>
                {
                    b.HasOne("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", "CodeProblemEntity")
                        .WithMany("TestCases")
                        .HasForeignKey("CodeProblemEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeProblemEntity");
                });

            modelBuilder.Entity("Application.Infrastructure.Entities.EntityExecutorCode.CodeProblemEntity", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
